### ISSUE TITLE
homography.pynb error

### ISSUE THREAD

**Issue by robmarkcole** [kornia/tutorials#22]
Also another error in this notebook:

```
[Errno 2] No such file or directory: 'sharpening.mp4'
``` 

should be mp4 in the earlier cell but is avi

**Comment by ducha-aiki** [comment]
Try to click on the "Open in Colab" link after cleaning the the cache, it seems to be an old version.
'sharpening.mp4' is part of this repo to show up on the https://kornia-tutorials.readthedocs.io/en/latest/image_registration.html
And the sharpenin.avi is what is generated. 

![image](https://user-images.githubusercontent.com/4803565/133089667-caf96032-49a8-49c7-a3f7-84da269186c3.png)

**Comment by robmarkcole** [comment]
confirm resolved
