### ISSUE TITLE
Minor broken code in Total Variation Denoising Notebook

### ISSUE THREAD

**Issue by utsavnandi** [kornia/tutorials#34]
Notebook: https://github.com/kornia/tutorials/blob/master/source/total_variation_denoising.ipynb

The cell number 7 breaks in the website:

https://kornia-tutorials.readthedocs.io/en/latest/total_variation_denoising.html

I am guessing this is because of pytorch version mismatch ? Happy to submit a PR.

**Comment by edgarriba** [comment]
right, the items goes out. Feel free to fix
