### ISSUE TITLE
DISK matching is featured twice on the website

### ISSUE THREAD

**Issue by jatentaki** [kornia/tutorials#73]
https://kornia.github.io/tutorials/

![image](https://github.com/kornia/tutorials/assets/22394841/0081790a-2d7b-4a98-8ea2-749efe95bf59)

**Comment by edgarriba** [comment]
Seems that the header for the lightglue got a copy paste artifact ?https://github.com/kornia/tutorials/blob/master/nbs/image_matching_lightglue.ipynb

**Comment by jatentaki** [comment]
Perhaps? But both headers seem to link to the same DISK (not LightGlue) tutorial
