### ISSUE TITLE
Wrong date for tutorial Image matching with lightglue

### ISSUE THREAD

**Issue by jurneo** [kornia/tutorials#78]
[Image matching example with LightGlue and DISK](https://kornia.github.io/tutorials/nbs/image_matching_lightglue.html) is shown with date May 2024

**Comment by johnnv1** [comment]
i guess it should be the data format, other tutorials are in mm-dd-yyyy, so update the tutorial header to 11-17-2023. @jurneo can you test and put a PR for this?

**Comment by jurneo** [comment]
@johnnv1 this is the PR: https://github.com/kornia/tutorials/pull/80
